apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  type: NodePort
  selector:
    app: web-server
  ports:
    - port: 80        # Port expose on local machine
      targetPort: 80  # Port exposed in Container
      nodePort: 30080 # 30000 - 32767