apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels: 
    app: mongo
spec:
  containers:
    - name: mongo
      image: mongo
      ports: 
        - containerPort: 27017
      volumeMounts:
        - name: mongo-vol
          mountPath: /data/db
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef: 
              name: mongo-creds
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mongo-creds
              key: MONGO_INITDB_ROOT_PASSWORD
  volumes:
    - name: mongo-vol
      persistentVolumeClaim: 
        claimName: mongo-pvc