apiVersion: v1
kind: Pod
metadata:
  name: mongo-express
  labels: 
    app: mongo-express
spec:
  containers:
    - name: mongo-express
      image: mongo-express
      ports:
        - containerPort: 8081
      env:
        - name: ME_CONFIG_MONGODB_AUTH_USERNAME
          valueFrom: 
            secretKeyRef: 
              name: mongo-creds
              key: MONGO_INITDB_ROOT_USERNAME 
        - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mongo-creds
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongo-service
