apiVersion: v1
kind: Service
metadata:
  name: app-server-service
spec:
  type: NodePort
  selector:
    app: app-server
  ports:
    - port: 3000        # Port expose on local machine
      targetPort: 3000  # Port exposed in Container
      nodePort: 30300 # 30000 - 32767 